### ISSUE TITLE
Add commanline support for reinit

### ISSUE THREAD

**Issue by KlausJokinen** [r-Larch/MouseTrap#3]
Commandline support for reinit command would be great. Currently if you resume from sleep, you need to do "reinit" from tray bar. It would be easier if we could just add a task to do this and call reinit via commandline.

**Comment by r-Larch** [comment]
Hello KlausJokinen, it's much more stable now, so it shouldn't be necessary to reinit it anymore. 
But to be sure I've added the desired command line flag. Use it like:
```CMD
cmd> mousetrap --reinit
```
And it will reinit the worker of the currently running instance, and if there is no running instance then it does nothing.

Download version: [v1.0.2-beta](https://github.com/r-Larch/MouseTrap/releases/tag/v1.0.2)
