### ISSUE TITLE
Anything like this for Mac?

### ISSUE THREAD

**Issue by merlinpatt** [r-Larch/MouseTrap#4]
I understand a port would be challenging but have you seen anything similar to this built for Macs?

**Comment by r-Larch** [comment]
Hi @merlinpatt,

I have little to no experience with Macs and porting this would require a total rewrite of everything in .NET Core WPF and then I would need a Mac to implement and test the MacOS specific part and at the moment, I have no time for this Project.

I hope you find something that works for you, 
and if you do, feel free to share your finding here!
It could help if I ever try to make a port.

**Comment by merlinpatt** [comment]
Thanks for replying! Definitely wasn't expecting a port. I know from experience how difficult that can be even if you do have the necessary devices.

I haven't found any existing tools yet for Mac nor have I found any decent tutorials that could guide me in building it myself. I fear that this might be something Apple restricts though I hope not.

It's baffling that this isn't a built in option. Your solution makes me wish I had a Windows machine again to use it
