### ISSUE TITLE
Window sizes

### ISSUE THREAD

**Issue by tkielarbb** [r-Larch/MouseTrap#6]
Hi,
Your program is great and uses much less resources than competition in form of  LittleBigMouse.
However is there a way to implement dragging resized windows? so the transition from bigger to smaller monitor looks seamless?

**Comment by r-Larch** [comment]
The graphical aspect of dragging a window between screens gets handled by the operating system itself.
The only thing I can control is the path where the mouse moves and with all improvements of v1.0.6 I hope 
the transition/teleportation runs much more smoothly.

I hope this helps somehow.
